/**
 * @module countries
 * @description 国・地域の定数データ。国コード・国名（日英）・国旗絵文字のマスタリストと、国名から国情報を取得するヘルパー関数を提供する。
 */
export const COUNTRIES = [
  { code: "DZ", nameJa: "アルジェリア", nameEn: "Algeria", flag: "🇩🇿" },
  { code: "JP", nameJa: "日本", nameEn: "Japan", flag: "🇯🇵" },
  { code: "US", nameJa: "アメリカ", nameEn: "USA", flag: "🇺🇸" },
  { code: "ENG", nameJa: "イングランド", nameEn: "England", flag: "🏴" },
  { code: "SCT", nameJa: "スコットランド", nameEn: "Scotland", flag: "🏴" },
  { code: "DE", nameJa: "ドイツ", nameEn: "Germany", flag: "🇩🇪" },
  { code: "FR", nameJa: "フランス", nameEn: "France", flag: "🇫🇷" },
  { code: "ES", nameJa: "スペイン", nameEn: "Spain", flag: "🇪🇸" },
  { code: "IT", nameJa: "イタリア", nameEn: "Italy", flag: "🇮🇹" },
  { code: "BR", nameJa: "ブラジル", nameEn: "Brazil", flag: "🇧🇷" },
  { code: "AR", nameJa: "アルゼンチン", nameEn: "Argentina", flag: "🇦🇷" },
  { code: "PT", nameJa: "ポルトガル", nameEn: "Portugal", flag: "🇵🇹" },
  { code: "NL", nameJa: "オランダ", nameEn: "Netherlands", flag: "🇳🇱" },
  { code: "BE", nameJa: "ベルギー", nameEn: "Belgium", flag: "🇧🇪" },
  {
    code: "BA",
    nameJa: "ボスニア・ヘルツェゴビナ",
    nameEn: "Bosnia and Herzegovina",
    flag: "🇧🇦",
  },
  { code: "CV", nameJa: "カーボベルデ", nameEn: "Cabo Verde", flag: "🇨🇻" },
  { code: "KR", nameJa: "韓国", nameEn: "South Korea", flag: "🇰🇷" },
  { code: "CW", nameJa: "キュラソー", nameEn: "Curacao", flag: "🇨🇼" },
  { code: "MX", nameJa: "メキシコ", nameEn: "Mexico", flag: "🇲🇽" },
  { code: "UY", nameJa: "ウルグアイ", nameEn: "Uruguay", flag: "🇺🇾" },
  { code: "HR", nameJa: "クロアチア", nameEn: "Croatia", flag: "🇭🇷" },
  { code: "DK", nameJa: "デンマーク", nameEn: "Denmark", flag: "🇩🇰" },
  { code: "SE", nameJa: "スウェーデン", nameEn: "Sweden", flag: "🇸🇪" },
  { code: "NO", nameJa: "ノルウェー", nameEn: "Norway", flag: "🇳🇴" },
  { code: "PL", nameJa: "ポーランド", nameEn: "Poland", flag: "🇵🇱" },
  { code: "CH", nameJa: "スイス", nameEn: "Switzerland", flag: "🇨🇭" },
  { code: "AT", nameJa: "オーストリア", nameEn: "Austria", flag: "🇦🇹" },
  { code: "CZ", nameJa: "チェコ", nameEn: "Czech Republic", flag: "🇨🇿" },
  { code: "TR", nameJa: "トルコ", nameEn: "Turkey", flag: "🇹🇷" },
  { code: "GR", nameJa: "ギリシャ", nameEn: "Greece", flag: "🇬🇷" },
  { code: "HT", nameJa: "ハイチ", nameEn: "Haiti", flag: "🇭🇹" },
  { code: "IR", nameJa: "イラン", nameEn: "IR Iran", flag: "🇮🇷" },
  { code: "IQ", nameJa: "イラク", nameEn: "Iraq", flag: "🇮🇶" },
  { code: "JO", nameJa: "ヨルダン", nameEn: "Jordan", flag: "🇯🇴" },
  { code: "RU", nameJa: "ロシア", nameEn: "Russia", flag: "🇷🇺" },
  { code: "UA", nameJa: "ウクライナ", nameEn: "Ukraine", flag: "🇺🇦" },
  { code: "NG", nameJa: "ナイジェリア", nameEn: "Nigeria", flag: "🇳🇬" },
  { code: "SN", nameJa: "セネガル", nameEn: "Senegal", flag: "🇸🇳" },
  { code: "CI", nameJa: "コートジボワール", nameEn: "Ivory Coast", flag: "🇨🇮" },
  { code: "GH", nameJa: "ガーナ", nameEn: "Ghana", flag: "🇬🇭" },
  { code: "CM", nameJa: "カメルーン", nameEn: "Cameroon", flag: "🇨🇲" },
  { code: "CD", nameJa: "コンゴ民主共和国", nameEn: "DR Congo", flag: "🇨🇩" },
  { code: "MA", nameJa: "モロッコ", nameEn: "Morocco", flag: "🇲🇦" },
  { code: "EG", nameJa: "エジプト", nameEn: "Egypt", flag: "🇪🇬" },
  { code: "AU", nameJa: "オーストラリア", nameEn: "Australia", flag: "🇦🇺" },
  { code: "NZ", nameJa: "ニュージーランド", nameEn: "New Zealand", flag: "🇳🇿" },
  { code: "CA", nameJa: "カナダ", nameEn: "Canada", flag: "🇨🇦" },
  { code: "CL", nameJa: "チリ", nameEn: "Chile", flag: "🇨🇱" },
  { code: "CO", nameJa: "コロンビア", nameEn: "Colombia", flag: "🇨🇴" },
  { code: "PE", nameJa: "ペルー", nameEn: "Peru", flag: "🇵🇪" },
  { code: "EC", nameJa: "エクアドル", nameEn: "Ecuador", flag: "🇪🇨" },
  { code: "CR", nameJa: "コスタリカ", nameEn: "Costa Rica", flag: "🇨🇷" },
  { code: "PA", nameJa: "パナマ", nameEn: "Panama", flag: "🇵🇦" },
  { code: "PY", nameJa: "パラグアイ", nameEn: "Paraguay", flag: "🇵🇾" },
  { code: "QA", nameJa: "カタール", nameEn: "Qatar", flag: "🇶🇦" },
  { code: "SA", nameJa: "サウジアラビア", nameEn: "Saudi Arabia", flag: "🇸🇦" },
  { code: "IE", nameJa: "アイルランド", nameEn: "Ireland", flag: "🇮🇪" },
  { code: "IS", nameJa: "アイスランド", nameEn: "Iceland", flag: "🇮🇸" },
  { code: "RS", nameJa: "セルビア", nameEn: "Serbia", flag: "🇷🇸" },
  { code: "SI", nameJa: "スロベニア", nameEn: "Slovenia", flag: "🇸🇮" },
  { code: "SK", nameJa: "スロバキア", nameEn: "Slovakia", flag: "🇸🇰" },
  { code: "ZA", nameJa: "南アフリカ", nameEn: "South Africa", flag: "🇿🇦" },
  { code: "TN", nameJa: "チュニジア", nameEn: "Tunisia", flag: "🇹🇳" },
  { code: "UZ", nameJa: "ウズベキスタン", nameEn: "Uzbekistan", flag: "🇺🇿" },
];

/**
 * チーム作成・試合プレビューで使う国旗絵文字マップ。
 * キーは Team.flag に保存される小文字英語名。
 */
export const FLAG_EMOJI: Record<string, string> = {
  algeria: "🇩🇿",
  argentina: "🇦🇷",
  australia: "🇦🇺",
  austria: "🇦🇹",
  belgium: "🇧🇪",
  bosnia_and_herzegovina: "🇧🇦",
  brazil: "🇧🇷",
  cabo_verde: "🇨🇻",
  cameroon: "🇨🇲",
  canada: "🇨🇦",
  chile: "🇨🇱",
  colombia: "🇨🇴",
  croatia: "🇭🇷",
  curacao: "🇨🇼",
  czechia: "🇨🇿",
  denmark: "🇩🇰",
  dr_congo: "🇨🇩",
  ecuador: "🇪🇨",
  egypt: "🇪🇬",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  france: "🇫🇷",
  germany: "🇩🇪",
  ghana: "🇬🇭",
  greece: "🇬🇷",
  haiti: "🇭🇹",
  iceland: "🇮🇸",
  iran: "🇮🇷",
  iraq: "🇮🇶",
  ireland: "🇮🇪",
  italy: "🇮🇹",
  ivory_coast: "🇨🇮",
  japan: "🇯🇵",
  jordan: "🇯🇴",
  mexico: "🇲🇽",
  morocco: "🇲🇦",
  netherlands: "🇳🇱",
  new_zealand: "🇳🇿",
  nigeria: "🇳🇬",
  norway: "🇳🇴",
  panama: "🇵🇦",
  paraguay: "🇵🇾",
  peru: "🇵🇪",
  poland: "🇵🇱",
  portugal: "🇵🇹",
  qatar: "🇶🇦",
  saudi_arabia: "🇸🇦",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  senegal: "🇸🇳",
  serbia: "🇷🇸",
  south_africa: "🇿🇦",
  south_korea: "🇰🇷",
  spain: "🇪🇸",
  sweden: "🇸🇪",
  switzerland: "🇨🇭",
  tunisia: "🇹🇳",
  turkiye: "🇹🇷",
  uruguay: "🇺🇾",
  usa: "🇺🇸",
  uzbekistan: "🇺🇿",
} as const;

const COUNTRY_CODE_TO_FLAG_TYPE: Record<string, string> = {
  DZ: "algeria",
  AR: "argentina",
  AU: "australia",
  AT: "austria",
  BE: "belgium",
  BA: "bosnia_and_herzegovina",
  BR: "brazil",
  CV: "cabo_verde",
  CM: "cameroon",
  CA: "canada",
  CL: "chile",
  CO: "colombia",
  HR: "croatia",
  CZ: "czechia",
  DK: "denmark",
  CD: "dr_congo",
  EC: "ecuador",
  EG: "egypt",
  ENG: "england",
  FR: "france",
  DE: "germany",
  GH: "ghana",
  GR: "greece",
  HT: "haiti",
  IS: "iceland",
  IR: "iran",
  IQ: "iraq",
  IE: "ireland",
  IT: "italy",
  CI: "ivory_coast",
  JP: "japan",
  JO: "jordan",
  MX: "mexico",
  MA: "morocco",
  NL: "netherlands",
  NZ: "new_zealand",
  NG: "nigeria",
  NO: "norway",
  PA: "panama",
  PY: "paraguay",
  PE: "peru",
  PL: "poland",
  PT: "portugal",
  QA: "qatar",
  SA: "saudi_arabia",
  SCT: "scotland",
  SN: "senegal",
  RS: "serbia",
  ZA: "south_africa",
  KR: "south_korea",
  ES: "spain",
  SE: "sweden",
  CH: "switzerland",
  TN: "tunisia",
  TR: "turkiye",
  UY: "uruguay",
  US: "usa",
  UZ: "uzbekistan",
};

// 国名から国情報を取得するヘルパー関数
export const getCountryInfo = (
  countryName: string,
  language: "ja" | "en",
): { flag: string; name: string } => {
  const country = COUNTRIES.find(
    (c) => c.nameJa === countryName || c.nameEn === countryName,
  );
  if (!country) return { flag: "🌍", name: countryName };
  return {
    flag: country.flag,
    name: language === "ja" ? country.nameJa : country.nameEn,
  };
};

export const getFlagTypeByCountryName = (
  countryName: string,
): string | undefined => {
  const country = COUNTRIES.find(
    (c) => c.nameJa === countryName || c.nameEn === countryName,
  );
  if (!country) return undefined;
  return COUNTRY_CODE_TO_FLAG_TYPE[country.code];
};
