import type {
  GradientPreset,
  SceneBackgroundPreferenceV1,
} from "@shared/types/SceneBackground";
import { DEFAULT_SCENE_BG_COLOR } from "./colors";

export const DEFAULT_SCENE_BACKGROUND: SceneBackgroundPreferenceV1 = {
  version: 1,
  mode: "solid",
  color: DEFAULT_SCENE_BG_COLOR,
};

export const TWO_COLOR_SCENE_BACKGROUND_GRADIENT_PRESETS: GradientPreset[] = [
  {
    id: "arena",
    name: "Arena",
    from: "#64748b",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#cbd5e1",
    angle: 165,
    colorCount: 2,
  },
  {
    id: "night-blue",
    name: "Night",
    from: "#0f172a",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#1e3a8a",
    angle: 135,
    colorCount: 2,
  },
  {
    id: "abyss",
    name: "Abyss",
    from: "#000000",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#0a0f1e",
    angle: 150,
    colorCount: 2,
  },
  {
    id: "midnight",
    name: "Midnight",
    from: "#020617",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#0f172a",
    angle: 180,
    colorCount: 2,
  },
  {
    id: "slate",
    name: "Slate",
    from: "#0f172a",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#334155",
    angle: 170,
    colorCount: 2,
  },
  {
    id: "carbon",
    name: "Carbon",
    from: "#111827",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#374151",
    angle: 160,
    colorCount: 2,
  },
  {
    id: "dusk",
    name: "Dusk",
    from: "#0f2027",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#203a43",
    angle: 150,
    colorCount: 2,
  },
  {
    id: "cobalt",
    name: "Cobalt",
    from: "#0d1b3e",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#1d4ed8",
    angle: 140,
    colorCount: 2,
  },
  {
    id: "ocean",
    name: "Ocean",
    from: "#0c4a6e",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#1d4ed8",
    angle: 135,
    colorCount: 2,
  },
  {
    id: "nordic",
    name: "Nordic",
    from: "#1e3a5f",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#0e7490",
    angle: 155,
    colorCount: 2,
  },
  {
    id: "indigo",
    name: "Indigo",
    from: "#1e1b4b",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#3730a3",
    angle: 145,
    colorCount: 2,
  },
  {
    id: "royal",
    name: "Royal",
    from: "#0d0221",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#4c1d95",
    angle: 140,
    colorCount: 2,
  },
  {
    id: "teal",
    name: "Teal",
    from: "#042f2e",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#0f766e",
    angle: 150,
    colorCount: 2,
  },
  {
    id: "forest",
    name: "Forest",
    from: "#052e16",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#166534",
    angle: 155,
    colorCount: 2,
  },
  {
    id: "crimson",
    name: "Crimson",
    from: "#1a0505",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#7f1d1d",
    angle: 145,
    colorCount: 2,
  },
  {
    id: "amber",
    name: "Amber",
    from: "#1c0a00",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#78350f",
    angle: 140,
    colorCount: 2,
  },
  {
    id: "violet-haze",
    name: "Violet Haze",
    from: "#140f2d",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#7c3aed",
    angle: 136,
    colorCount: 2,
  },
  {
    id: "steel",
    name: "Steel",
    from: "#111827",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#64748b",
    angle: 168,
    colorCount: 2,
  },
  {
    id: "ice",
    name: "Ice",
    from: "#083344",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#67e8f9",
    angle: 148,
    colorCount: 2,
  },
  {
    id: "matcha",
    name: "Matcha",
    from: "#14532d",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#86efac",
    angle: 150,
    colorCount: 2,
  },
  {
    id: "ruby",
    name: "Ruby",
    from: "#3f0713",
    mid: null,
    midPosition: 50,
    midWidth: 0,
    to: "#fb7185",
    angle: 143,
    colorCount: 2,
  },
];

export const THREE_COLOR_SCENE_BACKGROUND_GRADIENT_PRESETS: GradientPreset[] = [
  {
    id: "storm",
    name: "Storm",
    from: "#0f172a",
    mid: "#e2e8f0",
    midPosition: 50,
    midWidth: 0,
    to: "#0f172a",
    angle: 135,
    colorCount: 3,
  },
  {
    id: "studio",
    name: "Studio",
    from: "#09101c",
    mid: "#cdd8e6",
    midPosition: 28,
    midWidth: 0,
    to: "#334155",
    angle: 135,
    colorCount: 3,
  },
  {
    id: "aurora",
    name: "Aurora",
    from: "#042f2e",
    mid: "#0e7490",
    midPosition: 52,
    midWidth: 0,
    to: "#1e3a8a",
    angle: 145,
    colorCount: 3,
  },
  {
    id: "royal-neon",
    name: "Royal Neon",
    from: "#0d0221",
    mid: "#7c3aed",
    midPosition: 48,
    midWidth: 0,
    to: "#2563eb",
    angle: 138,
    colorCount: 3,
  },
  {
    id: "sunset",
    name: "Sunset",
    from: "#2d0b00",
    mid: "#ea580c",
    midPosition: 46,
    midWidth: 0,
    to: "#facc15",
    angle: 132,
    colorCount: 3,
  },
  {
    id: "forest-mist",
    name: "Forest Mist",
    from: "#052e16",
    mid: "#15803d",
    midPosition: 50,
    midWidth: 0,
    to: "#a7f3d0",
    angle: 155,
    colorCount: 3,
  },
  {
    id: "ember",
    name: "Ember",
    from: "#1a0505",
    mid: "#b91c1c",
    midPosition: 44,
    midWidth: 0,
    to: "#f59e0b",
    angle: 142,
    colorCount: 3,
  },
  {
    id: "cosmos",
    name: "Cosmos",
    from: "#030712",
    mid: "#4338ca",
    midPosition: 50,
    midWidth: 0,
    to: "#ec4899",
    angle: 140,
    colorCount: 3,
  },
  {
    id: "lagoon",
    name: "Lagoon",
    from: "#082f49",
    mid: "#06b6d4",
    midPosition: 52,
    midWidth: 0,
    to: "#a5f3fc",
    angle: 147,
    colorCount: 3,
  },
  {
    id: "inferno",
    name: "Inferno",
    from: "#270000",
    mid: "#dc2626",
    midPosition: 47,
    midWidth: 0,
    to: "#fbbf24",
    angle: 138,
    colorCount: 3,
  },
  {
    id: "grape-soda",
    name: "Grape Soda",
    from: "#1e1b4b",
    mid: "#8b5cf6",
    midPosition: 50,
    midWidth: 0,
    to: "#f0abfc",
    angle: 141,
    colorCount: 3,
  },
  {
    id: "mint-pop",
    name: "Mint Pop",
    from: "#064e3b",
    mid: "#34d399",
    midPosition: 50,
    midWidth: 0,
    to: "#d1fae5",
    angle: 154,
    colorCount: 3,
  },
  {
    id: "dawn",
    name: "Dawn",
    from: "#312e81",
    mid: "#f472b6",
    midPosition: 49,
    midWidth: 0,
    to: "#fde68a",
    angle: 128,
    colorCount: 3,
  },
  {
    id: "toxic",
    name: "Toxic",
    from: "#052e16",
    mid: "#84cc16",
    midPosition: 45,
    midWidth: 0,
    to: "#bef264",
    angle: 150,
    colorCount: 3,
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    from: "#4c0519",
    mid: "#fb7185",
    midPosition: 48,
    midWidth: 0,
    to: "#fde68a",
    angle: 134,
    colorCount: 3,
  },
  {
    id: "galaxy",
    name: "Galaxy",
    from: "#020617",
    mid: "#2563eb",
    midPosition: 50,
    midWidth: 0,
    to: "#a855f7",
    angle: 143,
    colorCount: 3,
  },
  {
    id: "mango",
    name: "Mango",
    from: "#7c2d12",
    mid: "#fb923c",
    midPosition: 46,
    midWidth: 0,
    to: "#fef08a",
    angle: 132,
    colorCount: 3,
  },
];

export const SCENE_BACKGROUND_GRADIENT_PRESETS: GradientPreset[] = [
  ...TWO_COLOR_SCENE_BACKGROUND_GRADIENT_PRESETS,
  ...THREE_COLOR_SCENE_BACKGROUND_GRADIENT_PRESETS,
];

export const PITCH_COLOR_PRESETS = [
  { id: "pitch-forest", name: "Forest", color: "#166534" },
  { id: "pitch-classic", name: "Classic", color: "#16a34a" },
  { id: "deep-grass", name: "Deep Grass", color: "#15803d" },
  { id: "stadium", name: "Stadium", color: "#22c55e" },
  { id: "emerald", name: "Emerald", color: "#10b981" },
  { id: "mint", name: "Mint", color: "#34d399" },
  { id: "olive", name: "Olive", color: "#65a30d" },
  { id: "lime", name: "Lime", color: "#84cc16" },
  { id: "moss", name: "Moss", color: "#4d7c0f" },
  { id: "pitch-teal", name: "Teal", color: "#0f766e" },
  { id: "cyan", name: "Cyan", color: "#0891b2" },
  { id: "night", name: "Night", color: "#14532d" },
] as const;
