export {
  DEFAULT_FORMATIONS,
  DEFAULT_FUTSAL_FORMATIONS,
  DEFAULT_EIGHT_ASIDE_FORMATIONS,
  DEFAULT_SOCIETY_FORMATIONS,
} from "./defaultFormations";
export { DEFAULT_TACTICS } from "./defaultTactics";
